### ISSUE TITLE
Winget version is out of date

### ISSUE THREAD

**Issue by JensMertelmeyer** [marcinotorowski/MSIX-Hero#107]
The current version on Winget is `2.0.64.0` whereas the current release is `2.0.68.0` (414159e).

I saw your remark 
> Winget repository is moderated. Usually, it may take a few days for new version to show up here.

but it has been more than a few days. Did you forget?

**Comment by marcinotorowski** [comment]
Correct, there is a mismatch. Will be fixed soon, likely with a new version that comes soon.

**Comment by marcinotorowski** [comment]
Pull request submitted: https://github.com/microsoft/winget-pkgs/pull/10491
