### ISSUE TITLE
Root element is missing

### ISSUE THREAD

**Issue by mabrochu-helpox** [marcinotorowski/MSIX-Hero#108]
Hi, i try to package a folder to MSIX but i always have this error

![image](https://user-images.githubusercontent.com/69210101/112753069-213d3500-8fa4-11eb-845b-c0bbd1d6a7cc.png)
![image](https://user-images.githubusercontent.com/69210101/112753086-37e38c00-8fa4-11eb-86f1-d496d13d1002.png)

**Comment by marcinotorowski** [comment]
A possible fix has been done in commit 84a9db447cb26ea6ac214b9beac2c330193c56ff.
Please check if this works after it. Alternatively, you can use the binaries from CI: https://ci.appveyor.com/api/buildjobs/825k1be038d8c6yq/artifacts/out%2FMSIX-Hero.zip

**Comment by marcinotorowski** [comment]
Can you retest with v2.2? (https://msixhero.net/2021/05/30/msix-hero-2-2-winget-v1-app-attach-and-productivity-enhancements/)?

**Comment by miracquel** [comment]
Hi,

Ijust installed MSIX hero and wanted to test it but I encountered the same error. 

![image](https://user-images.githubusercontent.com/85612866/121324250-1fe49d00-c943-11eb-8ce0-ad797e834897.png)

**Comment by marcinotorowski** [comment]
@miracquel Would it be possible to provide the content of the folder you are trying to pack? It does not have to be a productive package, can be easily stripped down from unrelated things, as long as it can reproduce this behavior.

**Comment by miracquel** [comment]
@marcinotorowski  here's the content of the folder.
![image](https://user-images.githubusercontent.com/85612866/121329203-92577c00-c947-11eb-987b-2f1e9b0e3be9.png)


i tried placing it to another location but seem to encounter the same error.

![image](https://user-images.githubusercontent.com/85612866/121328971-5cb29300-c947-11eb-88c6-6ec6d1ce393c.png)


this is my first time using this tool so I'm not sure if I'm missing anything that needs to be configured.

**Comment by marcinotorowski** [comment]
Before you can pack a directory, it must contain a manifest. For more information see https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-manual-conversion. I will consider adding the manifest automatically or provide a small builder tool in case it does not exist at the time of packing. You can also use various tools from Microsoft or third-party vendors to create MSIX files from scratch.

**Comment by marcinotorowski** [comment]
The previous commit adds some new options in case the user tries to pack a folder without a manifest.

![image](https://user-images.githubusercontent.com/22944216/121820549-c3abb100-cc93-11eb-9f9f-fe8dff2b5a39.png)

It is possible to decide which apps should be treated as entry points + which reg file is to be used as a registry. Other parameters are inferred from context. This is still not a repackaging though - converting an installer to a package should be done by Microsoft MSIX Packaging Tool or by third party vendors (https://docs.microsoft.com/en-us/windows/msix/partners).
