### ISSUE TITLE
Support for Modification- / Optional Packages when generating AppInstaller file

### ISSUE THREAD

**Issue by JoeHaenf** [marcinotorowski/MSIX-Hero#109]
AppInstaller also supports modification packages. These can be used to modify the base app (like modifying settings) or to extend functionality (like adding plugins).
When a company uses AppInstaller to distribute an app internally, it is very cumbersome to edit the AppInstaller file by hand each time a single modification package changes. There are lots of possibilites for error as you need to fill out all the identity fields correctly.

It would be great if MSIX Hero would support also to integrate modification packages into an AppInstaller file when you select them together with the main package.

*note for eventual testing:
Installing or updating AppInstaller files with modification packages may fail when using http(s):// as a base URI for hosted files. This is currently a known bug in the AppInstaller routines. Using file:// works fine, which makes this feature still usable for enterprise customers hosting their files on network shares.

**Comment by marcinotorowski** [comment]
Hi, thanks for your input.

This is most likely covered by the following implemented issue:
https://github.com/marcinotorowski/MSIX-Hero/issues/103

There is no official build available yet, but you can use artifact from CI (it is not digitally signed though, so no MSIX installation possible): https://ci.appveyor.com/api/buildjobs/snk95x5cna2l1y6l/artifacts/out%2FMSIX-Hero.zip

An official build should be ready soon, at the time of writing there are two pending issues blocking the release:
https://github.com/marcinotorowski/MSIX-Hero/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.1

**Comment by JoeHaenf** [comment]
Awesome! I tried it out and it looks very good.
Two things still would be a charm:
- Enable multiselection for adding existing packages (adding more than one in one go)
- Auto populate the URI field for each optional package the same way it is done for the main package
