### ISSUE TITLE
Allow further inspection of package content on function "Open MSIX Package"

### ISSUE THREAD

**Issue by JoeHaenf** [marcinotorowski/MSIX-Hero#111]
Open MSIX Package lets you analyze the package identity and dependencies quickly, wich is good. 

For me, I miss a possibility to inspect the package contents more in detail:
I would like to browse the registry contents of a package when I need to check if a certain configuration is really packaged. For file contents I would like to be able to open the manifest file or any other config file with my default editor to inspect the configuration.

This is the only remaining use case I still need the original MSIX Packaging Tool on a daily basis.

**Comment by marcinotorowski** [comment]
Below are some screenshots from the current state (last commit)

Files and folders:
![image](https://user-images.githubusercontent.com/22944216/120085008-0cc90600-c0d5-11eb-9305-884598602314.png)

Registry:
![image](https://user-images.githubusercontent.com/22944216/120085013-194d5e80-c0d5-11eb-8c49-5758fc18fb9d.png)

Still missing is an option to export/view files.

**Comment by marcinotorowski** [comment]
Fully implemented in [v2.2](https://github.com/marcinotorowski/MSIX-Hero/releases/tag/v2.2.0)
