### ISSUE TITLE
Missing PFX file error when using installed certificate

### ISSUE THREAD

**Issue by JoeHaenf** [marcinotorowski/MSIX-Hero#112]
When I try to create and sign a MSIX package, I get the error that the PFX file path would be emtpy, even when I am using a locally installed certificate.
![image](https://user-images.githubusercontent.com/53969751/114988405-98c0fe80-9e96-11eb-8cfd-0dad3d88cb12.png)

To be able to sign the package, I need to switch over to "Sign with PFX file" and then back.

**Comment by JoeHaenf** [comment]
Version used is 2.1.0.0

**Comment by marcinotorowski** [comment]
This is going to be available in CI build
https://ci.appveyor.com/project/marcinotorowski/msix-hero-bj0mu/builds/38847062/artifacts

Update of the official build on msixhero.net will be done in a few days.

**Comment by marcinotorowski** [comment]
Preview, signed build is now available in the Releases page:
https://github.com/marcinotorowski/MSIX-Hero/releases/tag/v2.1.4.0-pre
