### ISSUE TITLE
Hope to add multilingual support

### ISSUE THREAD

**Issue by Gaoyifei1011** [marcinotorowski/MSIX-Hero#121]
Currently, the default interface of the Msix Hero app is in English. Hopefully, in future versions, multi-language support will be added and language change options will be added in the Settings.

目前Msix Hero应用默认界面是英文，希望在以后的版本中可以添加多语言支持，并能够在设置中添加语言修改选项。

**Comment by marcinotorowski** [comment]
From this commit on https://github.com/marcinotorowski/MSIX-Hero/commit/0a7e7b63bc2ae0f362eeb8e0755734d4fd446eab, MSIX Hero is localizable, currently in EN, DE and PL.

**Comment by Gaoyifei1011** [comment]
> From this commit on [0a7e7b6](https://github.com/marcinotorowski/MSIX-Hero/commit/0a7e7b63bc2ae0f362eeb8e0755734d4fd446eab), MSIX Hero is localizable, currently in EN, DE and PL.

好的，非常感谢您提供了本地化支持。那您能否在您的项目主页中说明一下具体流程是怎样是操作的呢？
Ok, thank you very much for your localization support. Can you explain how the process works in your project home page?
