### ISSUE TITLE
Hope to release Msix Hero on the Microsoft Store

### ISSUE THREAD

**Issue by Gaoyifei1011** [marcinotorowski/MSIX-Hero#122]
I sincerely hope that developers will release Msix Hero on the Microsoft Store to simplify access to their apps.
我真诚的希望开发者能够将Msix Hero发布到Microsoft Store中，简化应用获取的途径。

**Comment by marcinotorowski** [comment]
Microsoft Store release is on its way. It is currently blocked by a need to get a waiver for headless app. Once done, the app is going to go through the certification process.

**Comment by marcinotorowski** [comment]
The waiver has been granted, the app is now being certified.

**Comment by Gaoyifei1011** [comment]
祝贺。那想问一下什么时候有多语言支持呢
Congratulations. When will multilingual support be available

**Comment by marcinotorowski** [comment]
https://www.microsoft.com/store/productId/9N3LL1W6QCNT
