### ISSUE TITLE
App attach generation fails with access denied error

### ISSUE THREAD

**Issue by marcinotorowski** [marcinotorowski/MSIX-Hero#126]
The issue is not reproducible on all machines, has been reported by one of the user.

Sample command line, executed as system from a non-MSIX context using PSEXEC:

    msixherocli appattach --createScripts -d "<dir>" -p "<msix>"

With version 2.29 or 2.34 return the following: `Access to the path 'e:\System Volume Information' is denied.`

Version 1.x seems to be unaffected by the issue.

**Comment by marcinotorowski** [comment]
Some interesting part of the extended logging

```
2021-11-18
10:21:52.3225|INFO|Otor.MsixHero.Appx.WindowsVirtualDesktop.AppAttach.Strategy.AppAttachVolumeCreationMsixHeroStrategy|Starting service ShellHWDetection...
Access to the path 'e:\System Volume Information' is denied.
```

indicate that the failure happens on the very end (by now everything is in place, VHD created) and the only issue is that the service cannot be re-started. In the new version, this kind of behavior will be logged, but not end with exception. This should solve the problem.

**Comment by marcinotorowski** [comment]
Reportedly, the last fix did not fully resolve the issue. Some investigation pending, possibly a better logging is required for this non-reproducible issue.

**Comment by jacobegan1** [comment]
I too am getting this error on a fresh windows build with version 3.0.0.0.  The VHD gets created but no further steps are taken.
