### ISSUE TITLE
Add support for Dependencies section in App Installer file

### ISSUE THREAD

**Issue by qmatteoq** [marcinotorowski/MSIX-Hero#131]
As explained in the official documentation, the App Installer file supports a section called Dependencies, where you can declare the location of the MSIX packages with the required dependencies to run the apps, like VCLibs or Windows App SDK.
The current version of MSIX Hero supports adding optional packages and related packages, but not dependencies.

**Comment by marcinotorowski** [comment]
Hi, thanks for spotting this.

This has been already in the parser for quite a while
https://github.com/marcinotorowski/MSIX-Hero/blob/90f4e47cdef754f822e0f51f6432a866981fe953/src/Otor.MsixHero.AppInstaller/Entities/AppInstallerConfig.cs#L70

Time to bring the feature in the UI.
