### ISSUE TITLE
Error while packaging application

### ISSUE THREAD

**Issue by 9072997** [marcinotorowski/MSIX-Hero#135]
To Reproduce:

1. Download [AuditionManager](http://audmgr.com/Programs/AuditionManagerPC.exe). This is a single-exe application with no installer.
2. Create a new folder containing just the EXE
3. Open MSIX Hero and select "Pack Directory -> MSIX"
4. Input the path to folder containing the single EXE
5. Click "Pack folder to MSIX package"
6. You will get the following error:

```
MakeAppx.exe returned exit code 1 due to error
C00CE169. App manifest validation error: The app
manifest must be valid as per schema: Line 20,
Column 123, Reason: violates minLength constraint
of '1'.
```

![image](https://user-images.githubusercontent.com/1310772/197553343-c8274fa5-f537-47a7-a9dc-113512e9cbbc.png)

I expect there is some metadata MSIX Hero is trying to pull from the EXE that isn't there. Is there some way to view the generated manifest so that I may edit it manually to fill in this missing information?

Thank you for the great tool. It has saved me a lot of time in packaging other things.

**Comment by marcinotorowski** [comment]
You can test a signed MSIX build from the following URL
https://msixhero.net/beta/msix-hero-2.3.112.0.msix
