### ISSUE TITLE
MSIX file doubles in size

### ISSUE THREAD

**Issue by Sigve-Fast** [marcinotorowski/MSIX-Hero#136]
After running the following command with the cli-tool the msix-file goes from 66mb to 161mb. Is that correct or is it a bug?
Running the latest code from the develop branch.

`.\msixherocli.exe edit app_x64.msix setRegistryValue 1234 --key HKEY_LOCAL_MACHINE\SOFTWARE\MyCompany\Keys--valueName MySpecialKey --type String`

**Comment by Sigve-Fast** [comment]
Made a PR with suggested fix: https://github.com/marcinotorowski/MSIX-Hero/pull/137

**Comment by marcinotorowski** [comment]
PR has been merged into `develop`, well spotted, thanks!
