### ISSUE TITLE
All packages (except of those installed from appinstaller) are hidden after a fresh installation of MSIX Hero

### ISSUE THREAD

**Issue by wjk** [marcinotorowski/MSIX-Hero#142]
On my shiny new Windows 11 VM (build 22621), MSIX Hero does not list any installed packages in either User or Machine scope. Nevertheless, there are dozens of packages in my WindowsApps folder even now. Furthermore, the event log viewer only displays two (seemingly random) Info-level events out of thousands and thousands of events visible in the Event Viewer. This condition persists after a refresh of either view. This also happened in a previous iteration of this VM (that I re-imaged to fix serious deployment errors), which makes it look like that it is a bug in MSIX Hero and not a problem with my configuration. My old Windows 10 PC has given up the ghost and will no longer turn on, so I cannot check there.

**Comment by marcinotorowski** [comment]
Hi @wjk,

this may be an UI bug in MSIX Hero, in which - after a fresh instalation - the default filter excludes all products having no appinstaller entry.

To verify, ensure the following checkbox is unticked:

![image](https://user-images.githubusercontent.com/22944216/210595235-cc9b15a5-3e59-44f9-8c16-9f6a8a9bfd43.png)

**Comment by wjk** [comment]
That did it, all right! Thanks so much!

**Comment by themerror** [comment]
The same problem, I hope it will be fixed as soon as possible.
