### ISSUE TITLE
Prepare VHD for App Attach

### ISSUE THREAD

**Issue by mobilejon** [marcinotorowski/MSIX-Hero#87]
Seems like it just creates an empty VHD, but not sure if thats by design or not.

**Comment by marcinotorowski** [comment]
Thanks @mobilejon for reporting this. The VHD should never be empty after a successful conversion. However, I have just tested several different MSIX packages with both stable releases 1.5 and the latest beta, all of them seem to produce correct results. 

Is it something that happens only for a specific package or it does not make any difference and fails for all? In case of the former,  could you provide a download link? Also, could you have a look in logs (`%localappdata%\Packages\MSIXHero-Preview_zxq1da1qqbeze\LocalCache\Local` ) if there is any warning or error?

**Comment by mobilejon** [comment]
I think I resolved it.

I’m trying to find a tool to resolve issues with WVD metadata errors.

No matter what process I use Azure cannot extract metadata.

Thanks and sorry for the false alarm

**Comment by marcinotorowski** [comment]
Great, should there be still something you think MSIX Hero should do better don't hesitate to open an issue or start a discussion.
